CREATE TABLE tb_usuarios(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL ,
    senha VARCHAR(255) NOT NULL,
    permissao VARCHAR(255) NOT NULL
);

CREATE TABLE tb_servicos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico VARCHAR(100) NOT NULL,
    preco NUMERIC(10,2) NOT NULL,
    duracao VARCHAR(100) NOT NULL
);

CREATE TABLE tb_agendamentos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_profissional INTEGER NOT NULL,
    id_servico INTEGER NOT NULL,
    data TIMESTAMP NOT NULL,
    status VARCHAR(100) NOT NULL,

    CONSTRAINT fk_agendamento_cliente
                            FOREIGN KEY (id_cliente)
                            REFERENCES tb_usuarios(id),
    CONSTRAINT fk_agendamento_profissional
                            FOREIGN KEY (id_profissional)
                            REFERENCES tb_usuarios(id),
    CONSTRAINT fk_agendamento_servicos
                            FOREIGN KEY (id_servico)
                            REFERENCES tb_servicos(id)
);